title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://zxv975.github.io/hcco-guide

aux_links:
  Template Repository: https://github.com/Zxv975/hcco-guide